/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CallbackPage: typeof import('./src/components/pages/CallbackPage.vue')['default']
    ErrorState: typeof import('./src/components/shared/ErrorState.vue')['default']
    FooterBar: typeof import('./src/components/shared/FooterBar.vue')['default']
    HeaderBar: typeof import('./src/components/shared/HeaderBar.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    LandingPage: typeof import('./src/components/pages/LandingPage.vue')['default']
    LoadingState: typeof import('./src/components/shared/LoadingState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
